# -*- coding: utf-8 -*-
"""Sobel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sF8DAMWBiQtWFoCn-PN8YvJth5_BI-J3
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt


img = cv2.imread("Hazlenut.png")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Gaussian blur (to remove noise)
blurred = cv2.GaussianBlur(gray, (5, 5), 1.4)
norm = cv2.equalizeHist(gray)

# Sobel Gradients
sobelx = cv2.Sobel(blurred, cv2.CV_64F, 1, 0, ksize=5)  # X direction
sobely = cv2.Sobel(blurred, cv2.CV_64F, 0, 1, ksize=5)  # Y direction
sobel_combined = cv2.magnitude(sobelx, sobely)

# Titles and images for plotting
titles = ["Original", "Blurred", "Norm", "SobelX", "SobelY", "Sobel"]
images = [img, blurred, norm, sobelx, sobely, sobel_combined]

# Plot results
plt.figure(figsize=(15, 6))
for i in range(len(images)):
    plt.subplot(1, 6, i+1)
    if len(images[i].shape) == 2:
        plt.imshow(images[i], cmap='gray')
    else:
        plt.imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))
    plt.title(titles[i])
    plt.axis("off")

plt.tight_layout()
plt.show()